### ISSUE TITLE
by default  if you pass something, this something equal true

### ISSUE THREAD

**Issue by ArtemSirobaba** [MrAndriy/Online_shop_React#22]
https://github.com/MrAndriy/Online_shop_React/blob/98b1a2c0ef0821af0a64f7a42f4bed95102b2cf1/client/src/pages/Home.jsx#L7

please debug 
 ```<Slides homeSlides={true} isNavigated={true} /> ```
and
```<Slides homeSlides isNavigated /> ```

same or not?

**Comment by MrAndriy** [comment]
Yes the same forgot 😅
